spectrum_dir: # contains full path of folder / directory with the files
weight_file: # contains path to the CSV file with weights. This is optional.
number_of_time_points: # number of time points collected.
out_dir: # output directory where the output CSV files will be created. Cannot be the same as spectrum_dir.